/*
 * This source file was generated by the Gradle 'init' task
 */
package org.todolist;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;

import org.junit.jupiter.api.Test;
import org.todolist.dao.TodoDAO;

public class AppTest {

    @Test
    public void testDBConnection() {
        try {
            TodoDAO todoDAO = new TodoDAO();
            Connection connection = todoDAO.getConnection();
            assertNotNull(connection, "Database connection should not be null");
            connection.close();
        } catch (SQLException e) {
            fail("Database connection failed: " + e.getMessage());
        }
    }
}
