/*
 * This source file was generated by the Gradle 'init' task
 */
package org.todolist;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.todolist.dao.TodoDAO;
import org.todolist.servlet.TodoServlet;
import org.todolist.utils.DatabaseConfig;

public class App {
    private static final Logger logger = Logger.getLogger(App.class.getName());
    private final TodoDAO todoDAO;

    public App() throws SQLException {
        this.todoDAO = new TodoDAO();
    }

    private boolean testDBConnection() {
        try (Connection conn = DatabaseConfig.getConnection()) {
            logger.info("Connected to the database!");
            return true;
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "Database connection failed", e);
            return false;
        }
    }

    private void startServer() throws Exception {
        Server server = new Server(8080);
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        server.setHandler(context);

        TodoServlet todoServlet = new TodoServlet(todoDAO);
        context.addServlet(new ServletHolder(todoServlet), "/todos/*");

        server.start();
        logger.info("Server started on port 8080");
        server.join();
    }

    public static void main(String[] args) {
        try {
            App app = new App();
            if (app.testDBConnection()) {
                app.startServer();
            } else {
                logger.severe("Exiting application due to database connection failure.");
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Application error", e);
        }
    }
}
